### PR TITLE
October Month Changes

### PR DESCRIPTION
**Pull request by ghost**
added the new meme , with october halloween feel, added a song reflected to the personality of swe's

### CODE REVIEW

**Comment by adigulalkari** [comment]
image
<br>
Can u erase this url on it

**Comment by adigulalkari** [comment]
Also remove the previous month jpeg

**Comment by ghost** [comment]
made all the required changes :)

**Comment by ghost** [comment]
> image
> Can u erase this url on it

done

**Comment by adigulalkari** [comment]
good job👏

**Pull request merged**
