### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ghost**
December Month Readme Changes

### CODE REVIEW

**Comment by adigulalkari** [comment]
Few issues:
1. Too much content
2. Content not center aligned
3. Unnecessary get started section
4. Dont require a heading for each section
5. Pls look into better memes they are a bit cringy
image
6. Doesnt fell the necessity of making this sentence as a quote

**Comment by ghost** [comment]
okay i'll do that

**Comment by adigulalkari** [comment]
@Jhwach it is the same image as 2023 december🤡..
#28 
Kindly update it

**Comment by ghost** [comment]
I don't know , sorry will replace that

**Comment by adigulalkari** [comment]
gg✨

**Pull request merged**
