### PR TITLE
Update readme for Spetember'24

### PR DESCRIPTION
**Pull request by raptor7197**
changed meme to bsod.jpg

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by adigulalkari** [comment]
get rid of the underline under the emoji. It clearly looks like an anchor tag

**Comment by adigulalkari** [comment]
also reduce the overall size of the meme.. its a bit too big..

**Comment by ghost** [comment]
> get rid of the underline under the emoji. It clearly looks like an anchor tag

ok ,

**Comment by adigulalkari** [comment]
@raptor7197 @ascendantaditya update?

**Comment by adigulalkari** [comment]
mb closing this

**Pull request closed without merging**
